### ISSUE TITLE
node vs nodejs

### ISSUE THREAD

**Issue by tofutim** [okTurtles/dnschain#147]
Hi, I'm working on installing dnschain, but running into 
```
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:431:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 3.16.0-31-generic
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/dnschain/node_modules/hiredis
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v0.10.10
gyp ERR! not ok 
npm WARN This failure might be due to the use of legacy binary "node"
```
since 'node' is actually 'nodejs'. Is there a schedule for updating dnschain? Should I install nodejs-legacy?

**Comment by taoeffect** [comment]
Uh, where are you getting that error? What lead up to that?

FYI, this is likely coming not from DNSChain, but one of its dependencies (`hiredis` most likely).

**Comment by tofutim** [comment]
You are absolutely right. It comes from the `hiredis` install
```
npm http GET https://registry.npmjs.org/wordwrap
npm http GET https://registry.npmjs.org/minimist
npm http 304 https://registry.npmjs.org/minimist
npm http 304 https://registry.npmjs.org/wordwrap
npm http GET https://registry.npmjs.org/binaryheap
npm http 304 https://registry.npmjs.org/binaryheap
gyp: Call to 'node -e "require('nan')"' returned exit status 1. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:431:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 3.16.0-31-generic
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/dnschain/node_modules/hiredis
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v0.10.10
gyp ERR! not ok 
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
```

**Comment by tofutim** [comment]
I'm building on 14.04 LTS. Maybe it is too old. Anyway, the problem is resolved by `apt-get install nodejs-legacy`

**Comment by taoeffect** [comment]
See also my comment about using `ln -s` in your PR (to link `nodejs` -> `node`). Closing for now since you seem to have figured out a solution.
