### ISSUE TITLE
Unhandled exception [$30]

### ISSUE THREAD

**Issue by pysiak** [okTurtles/dnschain#43]
Using the latest in npm I noticed I got this unhandled exception. Does it make any sense? Need more info?
```
2014-08-05T22:39:40.207Z - warn: [DNS] dropping query, NMC NS ~= localhost! (dns-handlers.coffee:119)
{ q:
   { name: 'soltysiak.bit',
     type: 1,
     class: 1 },
  nsIP: '178.216.201.222',
  info:
   { info:
      { description: 'Maciej Soltysiak Crypto Services',
        registrar: 'http://dc1.soltysiak.com' },
     ns:
      [ 'dc1.soltysiak.com',
        'fns1.42.pl',
        'fns2.42.pl' ],
     map:
      { '':
         { ns:
            [ 'dc1.soltysiak.com',
              'fns1.42.pl',
              'fns2.42.pl' ] } },
     email: 'maciej@soltysiak.com' } }

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: stream.push() after EOF
  at readableAddChunk (_stream_readable.js:146:15)
  at ResolverStream.Readable.push (_stream_readable.js:127:10)
  at ResolverStream.Transform.push (_stream_transform.js:140:32)
  at /usr/lib/node_modules/dnschain/src/lib/resolver-stream.coffee:97:55
  at Array.forEach (native)
  at [object Object].<anonymous> (/usr/lib/node_modules/dnschain/src/lib/resolver-stream.coffee:97:39)
  at [object Object].EventEmitter.emit (events.js:98:17)
  at [object Object].Request.handle (/usr/lib/node_modules/dnschain/node_modules/native-dns/lib/client.js:93:10)
  at [object Object].SocketQueue._onmessage (/usr/lib/node_modules/dnschain/node_modules/native-dns/lib/pending.js:154:9)
  at [object Object].EventEmitter.emit (events.js:98:17)
  at Socket.EventEmitter.emit (events.js:98:17)
  at UDP.onMessage (dgram.js:440:8)
```

**Comment by taoeffect** [comment]
This issue should be fixed in the upcoming 0.5 release based on the fix I mentioned earlier, but let us know if it's not!
